version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      ABSTRACT_API_KEY: ${ABSTRACT_API_KEY} 
      EXCHANGE_RATES_API_KEY: ${EXCHANGE_RATES_API_KEY}
